[app]
title = CDN SpeedTest
package.name = cdnspeedtest
package.domain = org.cdnspeedtest
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3,kivy,requests,pyjnius,android
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.2.1
fullscreen = 0
presplash_color = #2c3e50
icon = assets/icon.png
android.gradle_dependencies = ''
android.api = 33
android.minapi = 21
android.ndk = 25b
android.sdk = 33
android.archs = arm64-v8a, armeabi-v7a
android.accept_sdk_license = True
android.private_storage = True
android.wakelock = True
android.wifi = True
android.english_name = CDN SpeedTest
android.window = soft_input_mode
android.add_activity = True
android.add_activity_meta_data = yes
android.copy_libs = 1
android.entrypoint = main.py
android.manifest.intent_action = android.intent.action.MAIN
android.manifest.intent_category = android.intent.category.LAUNCHER
android.manifest.application_icon = @mipmap/icon
android.manifest.permissions = android.permission.INTERNET,android.permission.ACCESS_NETWORK_STATE,android.permission.ACCESS_WIFI_STATE
android.manifest.application_name = CDN SpeedTest
android.manifest.application_label = CDN SpeedTest

[buildozer]
log_level = 2
warn_on_root = 1
android.rebuild_icon = yes
